easy_admin:
  entities:
    User:
      class: App\Entity\User
      form:
        fields:
          - username
          - password
          # - email
          #- enabled
          #- lastLogin
          - roles
          # if administrators are allowed to edit users' passwords and roles, add this:
          #- { property: 'plainPassword', type: 'text', type_options: { required: false } }
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_TEST1': 'ROLE_ADMIN' , 'ROLE_TEST2': 'ROLE_ADMIN', 'ROLE_TEST3': 'ROLE_ADMIN', 'ROLE_TEST4': 'ROLE_ADMIN', 'ROLE_ADMIN': 'ROLE_ADMIN'} } }

  user:
    display_name: true
    display_avatar: false

  site_name: 'ACME <em style="font-size: 80%;">Megacorp.</em>'

# MORE See https://symfony.com/doc/master/bundles/EasyAdminBundle/integration/fosuserbundle.html
